[package]
name = "algo_data"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "quick_sort"
harness = false

[lib]
name = "quick_sort"
path = "src/quick_sort.rs"

[dependencies]
rand = "0.9.1"
